# Generated by Django 5.0.1 on 2024-01-12 08:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="token",
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Pending", "Pending"),
                    ("Confirmed", "Confirmed"),
                    ("Canceled", "Canceled"),
                    ("Visited", "Visited"),
                    ("Not Visited", "Not Visited"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
