# Generated by Django 5.0.1 on 2024-01-12 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "0002_booking_token_alter_booking_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="token",
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="doc_image",
            field=models.ImageField(upload_to="uploads/Doctors"),
        ),
        migrations.AlterField(
            model_name="slider",
            name="image",
            field=models.ImageField(upload_to="uploads/slider"),
        ),
    ]
